Dev
Julita45/zadanie-9.4-petle-choinka pull request #1
Opened 2017-12-01 21:23 UTC by Julita45

2017-12-03 13:56 UTC, matwjablonski requested changes

2017-12-03 13:56 UTC, matwjablonski commented on fullTree.js
> +	for (i=0; i<=a; i++) {
where is declaration for your iterator?

2017-12-03 13:56 UTC, matwjablonski commented on fullTree.js
> +		for (j=0; j<=(a-i); j++) {
same as above

2017-12-03 13:56 UTC, matwjablonski commented on fullTree.js
> +		for (k=0; k<=i*2; k++) {
same as above

2017-12-05 06:59 UTC, matwjablonski requested changes

2017-12-05 06:59 UTC, matwjablonski commented on fullTree.js
>  console.log(drawTree(5));
console.log here is unnecessary - you console.log your code in function ;)

2017-12-05 23:54 UTC, matwjablonski requested changes

2017-12-05 23:54 UTC, matwjablonski commented on fullTree.js
> +}
ok, but why you remove your call for this function?

2017-12-06 08:18 UTC, Julita45 commented
Ok, I get it ;)

2017-12-06 09:29 UTC, matwjablonski approved these changes

2018-01-07 10:17 UTC, merged